import { BeatData } from "@/interfaces/BeatData";

// Create 10 random beats
const beats: BeatData[] = [
  {
    id: "wgjbve",
    name: "2f05i2",
    src: "/beat.mp3",
    price: 8381,
    image: "/beat.jpg",
    userId: "0mbm0p",
    userName: "khecy9",
  },
  {
    id: "gtes5d",
    name: "901ilv",
    src: "/beat2.mp3",
    price: 3599,
    image: "/beat.jpg",
    userId: "gphc5",
    userName: "zdtulg",
  },
  {
    id: "v85w0n",
    name: "155mux",
    src: "/beat.mp3",
    price: 5382,
    image: "/beat.jpg",
    userId: "u4p7o9",
    userName: "gn045t",
  },
  {
    id: "chiqu8",
    name: "73o78g",
    src: "/beat2.mp3",
    price: 6991,
    image: "/beat.jpg",
    userId: "5odvug",
    userName: "79x3wl",
  },
  {
    id: "g8ld8",
    name: "6omuf",
    src: "/beat.mp3",
    price: 5472,
    image: "/beat.jpg",
    userId: "8q57lw",
    userName: "gnd47m",
  },
  {
    id: "d3u2u",
    name: "v5nvk6",
    src: "/beat2.mp3",
    price: 4958,
    image: "/beat.jpg",
    userId: "a3uvwv",
    userName: "25i14k",
  },
  {
    id: "g3udx",
    name: "hvdlyi",
    src: "/beat.mp3",
    price: 4049,
    image: "/beat.jpg",
    userId: "lrvw1f",
    userName: "e7b0m",
  },
  {
    id: "8w5ii",
    name: "wq4hfn",
    src: "/beat2.mp3",
    price: 1508,
    image: "/beat.jpg",
    userId: "95nxvr",
    userName: "dtv0pc",
  },
  {
    id: "tito1",
    name: "gyx4el",
    src: "/beat.mp3",
    price: 9103,
    image: "/beat.jpg",
    userId: "c9hiwu",
    userName: "5j5x53",
  },
  {
    id: "pu34q",
    name: "rcet2n",
    src: "/beat2.mp3",
    price: 7846,
    image: "/beat.jpg",
    userId: "0u7i9",
    userName: "7zc9q",
  },
  {
    id: "9657jj",
    name: "pgq8g",
    src: "/beat.mp3",
    price: 9805,
    image: "/beat.jpg",
    userId: "i9uf4",
    userName: "3vy9bj",
  },
  {
    id: "stg14k",
    name: "wjb3ae",
    src: "/beat2.mp3",
    price: 536,
    image: "/beat.jpg",
    userId: "7rlmsb",
    userName: "482yev",
  },
  {
    id: "ny98hp",
    name: "ogafnk",
    src: "/beat.mp3",
    price: 9192,
    image: "/beat.jpg",
    userId: "b208b9",
    userName: "jio0mn",
  },
  {
    id: "ygz7g",
    name: "dtlr7a",
    src: "/beat2.mp3",
    price: 899,
    image: "/beat.jpg",
    userId: "sxc3wb",
    userName: "l53y5j",
  },
  {
    id: "i83428",
    name: "z3dyw",
    src: "/beat.mp3",
    price: 6494,
    image: "/beat.jpg",
    userId: "nv51f",
    userName: "4fxpt",
  },
  {
    id: "qva3bf",
    name: "3vf0jg",
    src: "/beat2.mp3",
    price: 990,
    image: "/beat.jpg",
    userId: "galrc",
    userName: "y1oyfb",
  },
  {
    id: "50r42n",
    name: "lwt1ig",
    src: "/beat.mp3",
    price: 3073,
    image: "/beat.jpg",
    userId: "ufr5q",
    userName: "4qhiqo",
  },
  {
    id: "zmq4d",
    name: "1e4w7",
    src: "/beat2.mp3",
    price: 7861,
    image: "/beat.jpg",
    userId: "ijsit",
    userName: "equm5a",
  },
  {
    id: "lxtlic",
    name: "g60zz",
    src: "/beat.mp3",
    price: 4330,
    image: "/beat.jpg",
    userId: "1qvcdp",
    userName: "crc8k",
  },
  {
    id: "64fkq8",
    name: "9f3kgz",
    src: "/beat2.mp3",
    price: 4647,
    image: "/beat.jpg",
    userId: "zdfezl",
    userName: "rv61ml",
  },
  {
    id: "tiz3t",
    name: "kzme9s",
    src: "/beat.mp3",
    price: 539,
    image: "/beat.jpg",
    userId: "bjuet9",
    userName: "kd42i",
  },
];

export function getBeatData(beatId: string) {
  return beats.find((beat) => beat.id === beatId);
}

export function getBeats() {
  return beats;
}

export function formatTime(time: number): string {
  const minutes = Math.floor(time / 60);
  const seconds = Math.floor(time % 60);
  return `${minutes}:${seconds.toString().padStart(2, "0")}`;
}
